import { promises as fsp } from "node:fs";
const d = "D:\\ai\\gongzuoqu\\tools\\world-formula-paper\\lecture4-merged\\_packs\\";
const A = JSON.parse(await fsp.readFile(d + "20-vol2a.json", "utf8"));
console.log("A[3] title=" + A.pages[3].title + " rows=" + A.pages[3].rows.length);
A.pages[3].rows[1].cells[0].lines[0] = { s: "一条「无论哪条路线成功，都能被解释成本院说对了」的期望，不够格当预测。", w: 700, f: "red", sz: 13 };
await fsp.writeFile(d + "20-vol2a.json", JSON.stringify(A, null, 1), "utf8");
const B = JSON.parse(await fsp.readFile(d + "21-vol2b.json", "utf8"));
console.log("B[8] title=" + B.pages[8].title + " cells=" + B.pages[8].rows[0].cells.length);
B.pages[8].rows[0].cells[2].lines[0] = { s: "它与「随便加一项就能得到想要的结果」", sz: 11, f: "navy" };
B.pages[8].rows[0].cells[2].lines.push({ s: "很难区分。", sz: 11, f: "navy" });
await fsp.writeFile(d + "21-vol2b.json", JSON.stringify(B, null, 1), "utf8");
console.log("quote fixes applied");
